# Generated by Django 5.1.4 on 2024-12-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_library_num_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
