# Generated by Django 5.1.4 on 2024-12-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
            ],
        ),
    ]
