# Generated by Django 5.1.4 on 2024-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='librarymanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_lm', models.TextField(max_length=200)),
                ('email_lm', models.TextField(max_length=200)),
                ('password_lm', models.TextField(max_length=200)),
            ],
        ),
    ]
