# Generated by Django 5.1.4 on 2024-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
