# Generated by Django 5.1.4 on 2024-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_library_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='num_students',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
