# Generated by Django 5.1.4 on 2025-01-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_studentprofile_bio_studentprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Base.customuser'),
        ),
    ]
