# Generated by Django 5.1.4 on 2025-01-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography of the student'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='field_of_study',
            field=models.CharField(blank=True, help_text="The student's major or field of study", max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Whether the student's profile is active"),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='Base.customuser'),
        ),
    ]
