# Generated by Django 5.1.5 on 2025-01-18 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymanagerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_manager_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
