# Generated by Django 5.1.5 on 2025-01-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_alter_librarymanagerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('library_manager', 'Library Manager')], max_length=50),
        ),
    ]
